apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: awokgvq4s-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:e62cb15ad3dc91adc1212d9b47a968788d379011@sha256:1c3eed13c4ac0b4b7268edde776fd2dfe9b38ea6d598fe6c4466a3151271fbe8
          name: container-image
